import {StyleSheet} from 'react-native';
import Colors from '../components/Colors';

export const leads_styles = StyleSheet.create({
  container: {
    padding: 10,
  },
  buttonStyle: {
    fontSize: 16,
    color: Colors.gray,
  },
  buttonStyleActive: {
    fontSize: 16,
    borderWidth: 1,
    borderColor: Colors.blue,
    borderRadius: 20,
    color: Colors.blue,
    paddingHorizontal: 10,
  },
  floatingBtn: {
    width: 50,
    height: 50,
    borderRadius: 50,
    backgroundColor: Colors.blue,
    position: 'absolute',
    bottom: 10,
    right: 10,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  itemGroup: {
    padding: 10,
    marginVertical: 5,
    marginHorizontal: 0,
    minHeight: 50,
    borderRadius: 10,
    backgroundColor: '#2c2c2c10',
  },
  itemHeading: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 5,
  },
  itemBody: {
    paddingHorizontal: 10,
  },
  titleFont: {
    fontSize: 16,
  },
  itemButton: {
    display: 'flex',
    flexDirection: 'row',
    columnGap: 6,
  },
  itemInputBox: {
    borderWidth: 1,
    borderColor: Colors.blue,
    borderRadius: 8,
    height: 40,
    marginVertical: 5,
    paddingHorizontal: 10,
    paddingVertical: 0,
    color: Colors.gray,
  },
  accordianInputBox: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    columnGap: 10,
    paddingTop: 0,
    paddingVertical: 10,
    paddingBottom: 10,
  },
  accordianInputTitle: {
    margin: 0,
    fontSize: 16,
    color: Colors.black,
  },
  accordianInputText: {
    margin: 0,
    paddingHorizontal: 3,
    paddingVertical: 0,
    flex: 1,
    borderBottomWidth: 1,
    borderColor: Colors.gray,
    color: Colors.black,
    fontSize: 16,
  },
  accordianButton: {
    borderWidth: 1,
    borderColor: Colors.blue,
    width: 130,
    borderRadius: 6,
    marginTop: 5,
    marginBottom: 3,
  },
});
